<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1581687480201" stop="1581687481557">
  <name>test02_employee</name>
  <labels/>
  <test-cases>
    <test-case start="1581687480201" status="failed" stop="1581687480578">
      <name>TestEmployee.test01_post_0_yzz_gz_0043</name>
      <failure>
        <message>AssertionError: True != False</message>
        <stack-trace>a = (&lt;test02_employee.TestEmployee testMethod=test01_post_0_yzz_gz_0043&gt;,)

    @wraps(func)
    def standalone_func(*a):
&gt;       return func(*(a + p.args), **p.kwargs)

e:\python33\lib\site-packages\parameterized\parameterized.py:518: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
scripts\test02_employee.py:26: in test01_post
    assert_common(self, r)
tools\assert_common.py:14: in assert_common
    self.assertEqual(success, r.get("success"))
E   AssertionError: True != False</stack-trace>
      </failure>
      <attachments>
        <attachment source="9439bb26-f9da-445f-8d62-2c4228c53fbe-attachment.txt" title="Captured log call" type="text/plain"/>
      </attachments>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="9884-MainThread"/>
        <label name="host" value="SKY-20191110VJI"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1581687480706" status="passed" stop="1581687480979">
      <name>TestEmployee.test02_put</name>
      <attachments>
        <attachment source="deefd916-ded1-4277-b0e7-39035e403b60-attachment.txt" title="Captured log call" type="text/plain"/>
      </attachments>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="9884-MainThread"/>
        <label name="host" value="SKY-20191110VJI"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1581687481056" status="passed" stop="1581687481271">
      <name>TestEmployee.test03_get</name>
      <attachments>
        <attachment source="c157b0b0-6efa-4922-9332-ceb6647f01b7-attachment.txt" title="Captured log call" type="text/plain"/>
      </attachments>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="9884-MainThread"/>
        <label name="host" value="SKY-20191110VJI"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1581687481334" status="failed" stop="1581687481557">
      <name>TestEmployee.test04_delete</name>
      <failure>
        <message>AssertionError: True != False</message>
        <stack-trace>self = &lt;test02_employee.TestEmployee testMethod=test04_delete&gt;

    def test04_delete(self):
        # 调用删除员工接口
        r = self.api.api_delete_employee()
        print("删除结果为：", r.json())
        # 断言
&gt;       assert_common(self, r)

scripts\test02_employee.py:49: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tools\assert_common.py:14: in assert_common
    self.assertEqual(success, r.get("success"))
E   AssertionError: True != False</stack-trace>
      </failure>
      <attachments>
        <attachment source="5df42403-db47-4c2c-bd3f-49e2f4d52143-attachment.txt" title="Captured log call" type="text/plain"/>
      </attachments>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="9884-MainThread"/>
        <label name="host" value="SKY-20191110VJI"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
